# Generated by Django 2.2 on 2021-06-22 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='VideoTag',
        ),
        migrations.CreateModel(
            name='VideoTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tube.Tag')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tube.Video')),
            ],
        ),
    ]
