# Generated by Django 2.2 on 2021-06-22 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0002_auto_20210621_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videotag',
            old_name='Tag',
            new_name='tag',
        ),
    ]
