# Generated by Django 3.2.5 on 2021-08-04 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoProfile',
        ),
    ]
