# Generated by Django 3.2.5 on 2021-08-04 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_delete_videoprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pfp_thumbnail',
        ),
    ]
