# Generated by Django 3.2.5 on 2021-08-04 23:46

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_profile_pfp_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pfp',
            field=imagekit.models.fields.ProcessedImageField(default='default_pfp.jpeg', upload_to='pfps/'),
        ),
    ]
