# Generated by Django 3.2.5 on 2021-08-05 00:32

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_profile_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pfp',
            field=imagekit.models.fields.ProcessedImageField(default='default_pfp.jpeg', upload_to=''),
        ),
    ]
